name: zabet_app
description: "Zabet Gym and Fitness Training Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  provider: ^6.1.2
  wakelock_plus: ^1.2.8
  vibration: ^2.0.1
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.4
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/lang/
    - assets/sounds/alarm.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  # إعدادات الأيقونة التكيفية لأندرويد لتكبير اللوجو ورسم خلفية منفصلة
  adaptive_icon_background: "#121212" # يمكنك تغييره للون الداكن المناسب للوجو
  adaptive_icon_foreground: "assets/images/app_logo.png"
